# Generated by Django 2.2.17 on 2020-12-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField()),
                ('votes_total', models.IntegerField()),
                ('image', models.ImageField(upload_to='mdeia/')),
                ('icon', models.ImageField(upload_to='media/')),
                ('body', models.TextField()),
            ],
        ),
    ]
